name: E2E tests

on:
  release:
    types: [created]
  pull_request:
    types: [opened,synchronize,reopened,edited]
    branches:
      - main 
#     paths:
#       - "Dockerfile"
#       - "**.go"
#       - "!**_test.go" # exclude test files to ignore unit test changes
#       - "e2e/**_test.go" # include test files in e2e again
#       - ".github/workflows/e2e-tests.yaml"
#       - "charts/**"
#       - "manifests/**"

env:
  REGISTRY: ghcr.io
  USERNAME: ${{ github.repository_owner }}
  IMAGE_NAME: ${{ env.REGISTRY }}/${{ github.repository }}-dev:PR${{ github.event.number }}
  PASSWORD: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build-and-push-syncer-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}
  
  build-vcluster-cli:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      
      - name: Build vcluster cli
        run: GO111MODULE=on GOFLAGS=-mod=vendor go build -ldflags="-X 'main.version=v1.1.1'" -v -o artifact/vcluster ./cmd/vclusterctl/main.go
      
      - name: Upload vcluster cli to artifact
        uses: actions/upload-artifact@v2
        with:
          name: vcluster
          path: artifact/vcluster
      
      - name: Test
        run: |
          vcluster version
